### ISSUE TITLE
[question] 4장 - CQRS를 통한 동시성 문제 해결

### ISSUE THREAD

**Issue by JasonYoo1995** [caffeine-library/release-everything#14]
## 질문

p.112에서 CQRS(Command Query Responsibility Separation, 명령 질의 역할 분리) 사용하면
많은 동시성 문제를 효과적으로 방지할 수 있다는 내용이 있는데요
관련 사례를 공유할 수 있으면 좋을 것 같습니다.

## 연관 챕터

#7 

---

@caffeine-library/readers-release-everything

**Comment by kth990303** [comment]
write 되는 동시에 read 되는 케이스를 방지할 수 있을 거 같음.
근데 저는 경험한 사례는 없습니다 🥲

트랜잭션 isolation level, 락으로 동시성 방지하는 케이스도 괜찮을거같네요

**Comment by kth990303** [comment]
재빈님)
AWS 에서 read/write api 분리가 되게 잘돼있다고 느꼈음.
get-*, list-*, put-*, update-*

IAM 정책에서도 위와 같이 분리가 되게 잘돼있음.
