### ISSUE TITLE
[chapter] 2장 - 사례 연구: 항공사를 멈추게 한 예외

### ISSUE THREAD

**Issue by kth990303** [caffeine-library/release-everything#2]
## 제목
2장 - 사례 연구: 항송가를 멈추게 한 예외

## 특이 사항
이번 주는 1장, 2장 모두 진행되는 주차입니다.

---

@caffeine-library/readers-release-everything

**Comment by binchoo** [comment]
책이 공유한 이슈 사례를 코멘트 해 보며 읽었습니다.

**[이슈 내용]**
> - 공항 키오스크와 IVR 서비스 마비
> - 항공 예약, 발권, 수속 지연으로 SLA 위반 뿐 아니라 공항 업무 부담 증가, 탑승객 불편, 항공기 착륙 지연 등으로 확산되어 신뢰도, 금전, 시간 손해를 끼친 사례

**[이슈 원인]**
💬 DB 전환시, 기존 DB에 붙은 Dangling JDBC 커넥션의 **생명주기**를 개발자가 **설계하지 않아서** 생긴 문제입니다. 서비스를 내리지 않은 채 무중단 전환했기 때문에 이 부분이 치명적이었습니다. 코드 보니까 특별한 커넥션 관리 프레임워크를 쓰시진 않은 거 같아요. 

💬 저는 개발자가 아니라 확언은 못 하지만, 개발 작업 중에는 테스트 통과를 위한 기능 요구사항 구현에 치중하다 보니,  SW와 인프라를 독립적으로 생각하게 되거나, 이쪽은 시야가 깜깜한 상태로 작업을 하게 될 것 같아요. `자바=이식성=플랫폼 독립` 같은 비즈니스 용어에 노출되다 보면, 응용이 올라갈 텃밭이 뭐 어쩐 상태이든 상관 없겠지 싶을 수도. 


> - 키오스크, IVR이 의존하는 CF(핵심기능) 서비스 내 **DB 커넥션 풀 관리 미비**
>    - 모든 JDBC 커넥션 점유로 DB 쿼리를 수행 불가 상태로 전 스레드 블럭 상태.
>    - 커넥션 생성 시점과 반환 시점 사이에 Active DB가 전환되어 `conn.close()`가 정상 처리되지 않음.  finally 구문이 가져온 환각 효과.
> - 상황 당시 HTTP 헬스 체크는 정상 동작하였음.
>    - 응용 관점에서 DB 텔레메트리가 미비된 상태로 서비스 관제 중이었다는 뜻.


💬 품질이 깨지면 기능이 깨진다는 격언에 입각해 보면,
  - `개발 운영 분리`로 개발자는 인프라 환경에 대한 가시성 이슈를 지님.
  - 운영 측도 개발자가 짠 커넥션 회수 정책에 대해. 그런게 있는지 관심도 없을 거고, 코드도 못 보고.
  - 그렇기에 운영은 응용 입장에서 DB 텔레메트리를 정의하지 않았고, 관제할 수 없었음. 관측성 이슈가 해결됬더라면 CF만 재부팅해도 되었을 것임.
  - Dangling 커넥션은 LB에서 이미 고려되는 이슈라서 인프라 유지보수 담당자들은 관련 정책을 알고 계셨을 수도 있었음. 여기에 입각해서 이중화 된 DB에서는 어떤 처리가 이뤄져야 할지 고찰할 기회가 있었을 법 합니다. 근데,, SA인 저 역시 스프링이 알아서 해 주겠지~로 결론 내렸었는데요. 이번 책을 통해 경각심을 얻었습니다.

**[추신]**
💬 제가 스프링 배울 때 퓨어 JDBC 사용 vs. JPA Repository 스닛펫 비교 코드를 많이 봤었는 데 `conn.close()` 부분 예외 처리는 없었던 것 같아요. 책 예제가 다중화 DB를 고려하지 않기 때문이겠지요?

💬굉장히 머리 띵한게 DB 커넥션 소진과 HTTP 헬스 체크가 무관하다는 점이네요. HTTP 쪽과 DB 연결 쪽 텔레메트리를 구분하여 수집해야 할 텐데 현업에선는 다들 이렇게 하고 계실까요?
