### ISSUE TITLE
[question] 로깅 전략 및 저장을 어떻게 하고 있는지 얘기해보아요

### ISSUE THREAD

**Issue by kth990303** [caffeine-library/release-everything#25]
### 배경
- 로그 양이 많아지면 저장 공간이 부족해집니다.
- 그렇다고 로그를 지나치게 적게 저장하거나, 지나치게 빠른 주기로 삭제한다면 정보 수집에 어려움을 겪게 됩니다.

### 토의하고 싶은 점
- 로그를 어떻게 저장하고 있는지
  - 저장 위치
  - 롤링 전략 
- 제가 참여하고 있는 프로젝트에선 특정 주기마다 S3로 보내기도 하고, kafka로 중앙 관리포인트 측으로 보내기도 하고 있습니다. (자세한 사항은 2/25 에 게더타운에서 얘기하면 좋을 거 같아요)
- S3 Glacier, EBS, 데이터센터 하드웨어 등 다양한 사례가 존재할 거 같아서 이야기 나누면 좋아보여서 이슈를 남겨요!

## 연관 챕터

#22 
#23 

---

@caffeine-library/readers-release-everything

**Comment by binchoo** [comment]
CloudWatch에 저장
- 결국 AWS에서 굴리는 입장에선, AWS 네이티브 구성이 초반에 편합니다. ElasticBeanstalk, AppRunner, ECS, Lambda 로그를 CW에 쌓아서 써 봤습니다.
- 진짜 작은 규모라면 에러로그를 찾아 보기에 나쁘진 않았습니다. 인스턴스가 확장되었을 때 로그를 집계해서 보는 쿼리를 짜야하는 게 스트레스였죠. 
- 대시보드 구축도 가능하니 본격적으로 꽂히신 분은 배워 보시면 좋을 듯 합니다. 
- 비용은 은근 비싸다는 느낌입니다. 1GB 저장에 0.5 달러인데. 두 세달 프로젝트에 40GB 정도 로그가 쌓였더라구요. 애먼 돈 내는 것 같아서 삭제 시일을 걸어줬습니다.

S3에 저장
- 데이터레이크 = 까고 보면 S3다. 
- BI 도구 연계나 비용도 함께 고려했을 때 S3에 로그를 내보내는 것은 일단 하면 되는 행동처럼 여겨집니다.
- 비용과 쿼리 속도 향상을 위한 S3 객체 수명주기랑, 파티셔닝 설계는 모범사례에서 하도 말하는 거라, 이 내용은 스터디 때 말씀드리겠습니다.

EBS에 저장
- 웹, 와스 볼륨이면 50GB 내외로 잡으실 것 같은데 구태여 로그를 내부에 쌓으시는 건 리스크가 있어 보입니다.
- EBS DeleteOnTermination을 활성하시면 이전에 말씀드렸듯 확장하다가 사고가 나실 수도 있어서.. 결국은 Agent 기반으로 클라우드나 별도 DB에 로그를 내보시는 구성을 하시는 것 같습니다.

요즘 관심 있게 봤던 건 
- OTel 및 CloudWatch Application Signals인데, 결국 텔레메트리 파이프라인도 AWS가 관리형으로 깔아주어 컨텍스트를 더 함유하는 Trace 생산성이 좋아졌다는 것입니다. 
- Trace 분석 관련해서는, 저번에 같이 의논했던 Pinpoint 솔루션이 흥미로웠습니다.
