### ISSUE TITLE
[keyword] 10장 - 제어 평면

### ISSUE THREAD

**Issue by kth990303** [caffeine-library/release-everything#30]
## 주제

'10장 - 제어 평면'을 읽고 내용을 요약하거나,  
중요✨ 하다고 생각하는 키워드 및 관련 설명을 코멘트로 달아주세요

## 연관 챕터

#29 

---

@caffeine-library/readers-release-everything

**Comment by leejaeseung** [comment]
## 제어 평면(control plane)

운영 부하를 성공적으로 수행하기 위해 이면에서 작동하는 모든 소프트웨어와 서비스
-> 사용자에 의해 사용되는 서비스 외의 **운영을 위한 서비스**들을 말하는 듯?

서비스의 규모에 따라 필수적이지 않을 수 있다.
ex) 로깅, 모니터링 툴, IP 관리 소프트웨어 등등

### p.277 자동화에는 판단 능력이 없다.
그저 주어진 입력에 대한 작업을 수행할 뿐이다. 장애같은 예상치 못한 상황을 복구하기 위해 자동화를 도입하는 건 예측 범위를 더 흐리는 일이 될 수 있다.

실제로 저희 팀에서도 옛날에 데드레터 재처리 로직을 자동화 해두었다가 장애 상황에 데드레터가 다시 데드레터를 발행해서 DB 가 터질 뻔한 적이 있어서 상당히 공감되는 부분이었습니다 ㅎㅎ

## 10.5.2 경제적 가치
모니터링 등의 운영 툴을 사용하는 것의 가치는 결국 운영 환경의 비용과 관련이 있다.

## 10.5.3 파편화의 위험
모두가 같은 시각으로 애플리케이션에 대한 분석을 할 수 있어야 한다. 즉, 하나의 툴로 여러 시각의 정보를 얻을 수 있는게 베스트다.

## 10.5.4 로그와 통계
- push 방식 : 인스턴스가 직접 로그를 밀어 넣어 주는 방식. 사내 툴로는 에러 알림용 Matrix?
- pull 방식 : 하나의 수집기가 각 인스턴스를 접근해서 인스턴스 로컬에 저장된 로그를 복사해가는 방식. 사내 툴로는 Pallas. 프로메테우스

## 10.8 명령과 제어

- 운영 환경의 인스턴스나 서비스에 대한 제어를 위해 어디까지 개발할 지를 잘 정해야 한다. (운영자, 개발자의 권한을 분리해 기능을 제한하기?)
- HTTP 를 통해 API 요청을 할 수 있게 하되, 관리용 API 를 따로 제공해야 한다.(internal)
- API 호출이 많이 필요하게 된다면, kafka 같은 메시지 큐 시스템을 고려하자.

## 결론

사용자에게 좋은 경험을 주어 경제적 가치를 늘리기 위해
정보를 수집하고 - **로깅**
장애를 파악해 - **얼럿**
복구해야 한다 - **구성 서비스, 배치 도구**
또, 빠르게(**자동화**) 위 동작을 하는 대신 안전성을 고려해야 한다.

**Comment by binchoo** [comment]
# 10장. 제어 평면

서비스를 성공적으로 수행하기 위해 이면에서 작동하는 모든 소프트웨어와 서비스

## 10.1. 적합도 평가
- 제어평면은 선택사항
  - 모니터링 -> 사후 분석, 사고 복구, 결함 발견을 도와주지만 필수는 아니다.
  - IP 관리 소프트웨어 -> 일정 작은 규모까지는 도입하지 않는 것이 더 좋다.
- 제어평면은 구현 비용과 운영 비용을 증가시킨다. 



## 10.2. 기계적 확대율
- 자동화로 문제를 일으킨 사례가 적지 않음
  - [AWS 버지니아 리전 S3 장애 사건](https://aws.amazon.com/ko/message/41926/)
  - "SaaS 시장 전반이 재부팅 되는 날": S3 강결합 고객들이 장애를 겪음
- 문제 사후 분석
  - S3 팀에서 S3용 서버를 일부를 제거하는 명령을 실행했으며, 잘못된 명령이 추가되어 더 많은 서버가 죽음
  - 자동화 처리가 예상보다 많은 처리량을 사라지게 했음
    - 자동화에는 판단 능력이 없고, 잘못 정의되어 있으면 급속히 시스템을 망가뜨릴 수 있음
  - 사람 실수로 치부하기 보다는, 시스템 장애로 정의해야 함
    - 인재가 아닌 시스템 장애라 인지하고, 정상 상황에서도 시스템을 사후 분석하고, 인사이트를 얻는 것이 중요 
    - 이전에는 동일한 절차가 잘 동작했고 문제가 없었으므로, 사후 분석에서는 어떤 조건이 차이가 있는지 확인 필요
      - (실수하지 않도록 동료 간 검수를 해줬는가)
      - (절차서가 개정이 되었는가)
      - (시스템이 피드백을 제공했었는가, 그 피드백이 문제 예방에 도움이 되었을까)

## 10.3. 플랫폼과 생태계

플랫폼 팀은 플랫폼에 안정과 성능을 확보하여 고객을 지원하는 직무이며, 선택한 기술이 품질 확보에 적합하지 않다면 개선한다.

- **플랫폼 팀> 모니터링 팀**의 책임
  - 모니터링 플랫폼(모니터, 트리거, 경보)을 구현하되, 모니터링은 하지 않아야 한다.
  - 고객이 스스로 모니터를 구성할 수 있도록 인프라, 에이전트 설치, JSON 문서 등 제공
  - 모니터링 팀은 개발 팀이 쓰는 **일종의 인터페이스 처럼 동작**해야 한다.

- **DBA**의 책임
  - 고성능, 안정적인 DB 플랫폼을 만들어 제공
  - 한계
    - 서버에서 잘 돌아갈 수 있도록 SQL 구문 적합성을 분석하고, 데이터 모델을 관리할 책임도 졌다
  - NoSQL 도입
    - 데이터 모델링을 어플리케이션 책임으로 넘길 수 있다
  - SQL 장점(?)
    - 서비스 별도로 DB를 두면 DBA 개입 없이 개발 팀이 자율적으로 확장 가능
  - 공용 SQL DB를 확장 플랫폼
    - Migration 프레임워크

## 10.4. 운영 수준 개발 환경

- 개발 서버는 언제 무너질지 모르는 쓰레기 더미
  - 버전 관리가 안 된 스크립트
  - 수많은 SSH 키들 

- QA 환경과 운영 환경의 괴리
  - 운영과 규모가 다름
  - 모의 서비스 사용
  - QA에 없고 운영에서만 동작하는 기능이 있기도 함
  - QA 데이터베이스는 현실과 다름 (개인고유식별정보 등)

- 관리책: 개발, QA 환경을 가상화/자동화
  - 사전에 미리 구성된 이미지를 통해, 개발 서버를 가상 머신으로 구성하기
  - QA 환경은 운영 배치와 동일한 자동화 도구로 찍어내기 / 모든 팀 필요에 따라 찍어낼 수 있도록 가상화하기
  - 운영 데이터를 배치로 긁어 익명 처리한 데이터를 QA에 이용하기

- 개발 플랫폼은 운영 수준의 SLA로 취급해야 한다. 개발 플랫폼이 동작하지 않으면 개발을 할 수 없다.
  - 버전 관리
  - CI/CD
  - QA 환경
  - 소스코드 저장소
