### ISSUE TITLE
[question] 개발 및 운영 환경을 어떻게 관리하고 계신가요?

### ISSUE THREAD

**Issue by leejaeseung** [caffeine-library/release-everything#31]
### 10.4 운영 수준 개발 환경
위 챕터에서 운영 및 개발, QA 환경에 대한 언급이 나왔는데요.
서로의 팀들에서 개발, QA, 운영 환경을 어떻게 관리하고 있는지 공유해 보는 것도 좋을 것 같아 질문 글로 올려봅니다. ㅎㅎ

저희 팀은
- **dev(develop 브랜치)** : pr 을 올렸지만 아직 approve 되지 않은 상태. 개발자가 기능을 테스트하고 수정하는 단계
- **sandbox(sandbox 브랜치)** : pr 이 approve 되면 sandbox 에 배포한다. 기획자가 테스트하는 단계. 
- **beta(master 브랜치)** : 배포 요청서가 승인되어야 배포가 가능하다. (개발자가 직접 배포) 실제 운영 인프라와 연결된다. 신규 프로젝트라면 QA 팀의 도움을 받아 테스트하고, 보통은 기획자가 테스트한다.
- **production(master 브랜치)** : beta 테스트 완료되면 운영 환경에 배포한다. SRE 팀이 배포한다. (개발자는 직접 배포 불가)
위처럼 관리하고 있는데, 각 팀의 방법마다의 장단점을 공유해보고 싶습니다~!

## 연관 챕터

#30 

---

@caffeine-library/readers-release-everything

**Comment by kth990303** [comment]
- dev (beta): pr 을 올렸지만 아직 approve 되지 않은 상태. 개발자가 기능을 테스트하고 수정하는 단계, 기획자도 여기서 테스트합니다.
- develop: qa 완료되면 여기로 merge. 브랜치만 존재하며, 이 환경은 존재하지 않습니다.
- master: 운영환경

**Comment by leejaeseung** [comment]
![image](https://github.com/caffeine-library/release-everything/assets/23518329/eeda1495-f4a5-4b7e-a24e-bf12be366ddc)

저희 팀에서 사용하는 git flow 인데, 조금 특이한 방식이어서 공유해 봅니다~
각 feature 들의 개발 및 배포가 개별적으로 진행되는 프로젝트에서 유용한 방식인 것 같아 혹시라도 나중에 git flow 를 변경하시게 된다면 참고가 되었으면 하네요 ㅎㅎ

### 장점
- 개발, 기획 테스트를 나눠서 개발이 덜 된 feature 를 테스트할 여지가 없음
- 테스트가 오래 걸리는 feature 가 있다면, 이후 개발된 feature 는 따로 배포가 가능 <- 이 부분 때문에 위 flow 를 적용하였습니다.
develop -> master 로 머지하는 flow 라면, develop 에서 테스트가 진행 중인데 급한 기능이 먼저 배포가 나가야 한다면 다른 기능들을 롤백하는 과정이 필요하니..


### 단점
- master 에서 develop, sandbox 를 매번 최신 버전으로 갱신해 주어야 함.

**Comment by emiling** [comment]
#### 팀에서 사용하는 방식

- feature : develop에서 따고, 새로운 신규 기능을 개발하거나 버그 수정 시 사용
- develop : 신규 기능들이 개발되고 머지되는 브랜치
- master : release를 머지하는 브랜치
- release : develop 에서 따고, 정규 배포 시점의 변경 사항들을 관리
- hotfix : master에서 따고, 운영에 나간 변경사항 중 급하게 오류를 수정해야하는 경우 사용하고 develop과 master 동시에 반영되어야함

#### 개인적으로... 

> 요약 : 정답은 없고 자신의 환경에 맞는 방식을 사용하고 그거에 대한 타당한 이유가 있으면 된다

- 무조건 프로젝트에 git flow를 적용하는 것이 옳다고 생각하진 않음 
  - 사실상 업계표준(?)이 되어 있기도 하고, 왜 쓰는지 명확한 이유 없이 git-flow를 채용하는 케이스가 많음
  - 적잡하지 않다고 생각하는 경우는...
    - 프로세스의 복잡도는 결국 배포 주기를 늦춰 피드백 지연을 발생시킴 (오류 발생 가능성 올라감)
    - 요즘같은 웹 기반 서비스에서처럼 소프트웨어를 지속적으로 빠른 주기로 배포하는 환경에서 적합하지 않음 (브랜치 수명)
    - 또한 릴리즈를 발행하며 해당 시점의 버전을 관리할 만큼 소프트웨어의 여러 버전을 지원해야하는 케이스가 많은가?  
- 자주 배포하는 것이 좋은가? 정규배포와 같은 시스템을 갖춰 특정 주기마다 배포하는 게 좋은가?
  - 이 또한 환경에 따라 다름.. 
  - B2B 서비스나 다수의 사람(클라이언트)들이 사용하는 프로그램에서는 의도적으로 릴리즈 주기를 따는게 좋을듯
- 최근엔 다른 대안으로 경량화된 `trunk` 기반의 플로우 (ex. github flow) 등 고려도 해볼법함
  - 그러나 아무래도 CI 환경이 견고하게 구축되지 않으면 운영 배포 시 불안정할듯
