### ISSUE TITLE
[additional] 오버라이딩이 되는 설정 파일 - HOCON

### ISSUE THREAD

**Issue by leejaeseung** [caffeine-library/release-everything#44]
## 연관 챕터
#42

## 조사 내용

15장 중간에 운영 환경 구성 및 재정의에 관한 내용이 나왔는데, 저희 팀에서 사용중인 환경 설정 파일인 .conf 파일을 간단히 소개드려 봅니다.
https://jason-heo.github.io/programming/2018/08/06/hocon.html
https://github.com/lightbend/config
자세한 설명은 링크로 대체합니다. ㅎㅎ hocon 관련 내용만 검색해서 보셔도 무방할 것 같아요

사용하면서 느낀 장점으로는
- 형식이 좀 더 자유롭고, 직관적이다. dot 으로 depth 를 표현할 수도 있고, json 형식을 사용할 수도 있다. : 혹은 = 모두 사용 가능하다.
- file override 가 가능하다. <- .conf 를 처음 접하신 시니어 개발자분께서도 되게 감탄을 하시더라구요.
설정 파일을 include 해서 사용하고, 동일한 depth 의 옵션만 override 가 가능합니다!

scala 에서만 사용 가능한가 싶어서 찾아보니 kotlin 의 ktor 에서도 지원을 한다고 하네요
(spring 은 안되나 봤는데, 옛날 옛적의 변환 라이브러리 하나정도..?)
spring 외의 새로운 프레임워크나 언어로 신규 프로젝트로 개발할 때 사용해보면 유용할 듯 합니다! ㅎㅎ

@caffeine-library/readers-release-everything

**Comment by binchoo** [comment]
내용 공유 감사합니다. 호옥시 구성설정 Override가 가능하다는 것이, 파일을 수정하면 실시간으로 반영된다는 기능일까요(Refreshing Bean?)

는 공식 문서 읽어보니까, 기존 객체에 대입된 값을 이후 라인에서 머지해 가면서 쓸 수 있다는 것 같군요!
- 기존에는 거의 똑같이 큰 크기의 설정 파일을 Profile별로 준비해야 했다면, 이제는 작은 파일로 쪼개둘 수 있다?
- 이 작은 파일들을 include 하는 형태로 원하는 설정을 골라 담을 수 있다.
```JSON
{
    "foo" : { "a" : 42 },  
    "foo" : { "b" : 43 }
}

{
   "foo" : { "a" : 42, "b" : 43 }
}
```
오버라이드로 예상되는 이점인데 실제로 어떠셨는지 나중에 공유 받을 수 있다면 좋겠습니다 ㅎㅎ
